"""Added purchase requisitions

Revision ID: 8179ed065897
Revises: a9de22d1db5a
Create Date: 2026-07-26 12:15:15.945122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8179ed065897'
down_revision = 'a9de22d1db5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requisitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pr_number', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('requested_by', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pr_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_requisitions')
    # ### end Alembic commands ###
