"""Added inventory transaction table

Revision ID: a9de22d1db5a
Revises: d5aabd1ff350
Create Date: 2026-07-21 13:15:47.321217

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a9de22d1db5a'
down_revision = 'd5aabd1ff350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.String(length=30), nullable=True),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('return_number'))

    op.drop_table('material_returns')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_returns',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('return_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('item_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('return_reason', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('returned_by', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('return_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('material_returns_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('material_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('return_number'), ['return_number'], unique=True)

    op.drop_table('inventory_transactions')
    # ### end Alembic commands ###
