"""Added purchase requisitions

Revision ID: b15655fed380
Revises: 8179ed065897
Create Date: 2026-07-26 12:16:53.762163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b15655fed380'
down_revision = '8179ed065897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requisitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=True))
        batch_op.alter_column('request_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_requisitions', schema=None) as batch_op:
        batch_op.alter_column('request_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.drop_column('priority')

    # ### end Alembic commands ###
