"""Add pr_id to purchase_orders

Revision ID: fa945fd9bf81
Revises: b15655fed380
Create Date: 2026-07-29 19:38:05.007899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa945fd9bf81'
down_revision = 'b15655fed380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pr_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'purchase_requisitions', ['pr_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pr_id')

    # ### end Alembic commands ###
